# Generated by Django 5.2.15 on 2026-06-04 17:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало")),
                (
                    "doors_open_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Открытие дверей"
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(max_length=255, verbose_name="Площадка"),
                ),
                ("venue_address", models.TextField(verbose_name="Адрес")),
                (
                    "venue_city",
                    models.CharField(
                        default="Москва", max_length=100, verbose_name="Город"
                    ),
                ),
                (
                    "venue_map_url",
                    models.URLField(blank=True, verbose_name="Ссылка на карту"),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/posters/",
                        verbose_name="Постер",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/banners/",
                        verbose_name="Баннер",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Фиксированная сумма"),
                            ("percent", "Процент"),
                        ],
                        max_length=10,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Размер скидки"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Макс. использований"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="Использовано"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует с"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если пусто — применяется ко всем событиям",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Цена (руб.)",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(verbose_name="Всего билетов"),
                ),
                (
                    "sold_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Продано"),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Зарезервировано"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Отображать"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип билета",
                "verbose_name_plural": "Типы билетов",
                "ordering": ["sort_order", "price"],
                "unique_together": {("event", "name")},
            },
        ),
    ]
