# Generated by Django 5.2.15 on 2026-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="fighter_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Боец 1 — имя"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="fighter_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/fighters/",
                verbose_name="Боец 1 — фото",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="opponent_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Боец 2 — имя"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="opponent_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/fighters/",
                verbose_name="Боец 2 — фото",
            ),
        ),
    ]
