# Generated by Django 5.2.15 on 2026-06-04 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Email"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "consent_given_at",
                    models.DateTimeField(null=True, verbose_name="Согласие дано"),
                ),
                (
                    "consent_ip",
                    models.GenericIPAddressField(null=True, verbose_name="IP согласия"),
                ),
                (
                    "offer_accepted_at",
                    models.DateTimeField(null=True, verbose_name="Оферта принята"),
                ),
            ],
            options={
                "verbose_name": "Покупатель",
                "verbose_name_plural": "Покупатели",
            },
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_type",
                    models.CharField(max_length=50, verbose_name="Тип согласия"),
                ),
                (
                    "document_version",
                    models.CharField(max_length=20, verbose_name="Версия документа"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP")),
                ("user_agent", models.TextField(verbose_name="User-Agent")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_logs",
                        to="orders.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал согласий",
                "verbose_name_plural": "Журнал согласий",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за штуку"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Итого"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("canceled", "Отменён"),
                            ("refunded", "Возвращён"),
                            ("expired", "Истёк"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "ip_address",
                    models.GenericIPAddressField(null=True, verbose_name="IP"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.customer",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="events.promocode",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="events.tickettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_number",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="Номер билета",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Токен"
                    ),
                ),
                (
                    "verify_code",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Код проверки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Выдан"),
                            ("used", "Использован"),
                            ("canceled", "Отменён"),
                            ("expired", "Истёк"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tickets/pdf/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email отправлен"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Билет",
                "verbose_name_plural": "Билеты",
                "ordering": ["-created_at"],
            },
        ),
    ]
