# Generated by Django 5.2.15 on 2026-06-04 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("offer", "Публичная оферта"),
                            ("privacy", "Политика конфиденциальности"),
                            ("consent", "Согласие на обработку ПД"),
                            ("refund", "Правила возврата"),
                            ("legal", "Реквизиты"),
                            ("cookies", "Политика cookies"),
                            ("terms", "Пользовательское соглашение"),
                            ("delivery", "Доставка и оплата"),
                        ],
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(verbose_name="Содержание (HTML/Markdown)"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Версия"
                    ),
                ),
                (
                    "updated_at_display",
                    models.DateField(verbose_name="Дата актуализации"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
