# Generated by Django 5.2.15 on 2026-06-04 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="YK Event ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Тип события"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="YK Payment ID",
                    ),
                ),
                ("raw_body", models.JSONField(verbose_name="Тело")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Получен"),
                            ("processed", "Обработан"),
                            ("failed", "Ошибка"),
                            ("skipped", "Пропущен"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        null=True, verbose_name="IP отправителя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook-событие",
                "verbose_name_plural": "Webhook-события",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "yookassa_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="YooKassa ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("waiting_for_capture", "Ожидает захвата"),
                            ("succeeded", "Успешен"),
                            ("canceled", "Отменён"),
                            ("refunded", "Возвращён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "confirmation_url",
                    models.URLField(blank=True, verbose_name="URL подтверждения"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оплачено"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Возвращено"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Сумма возврата",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(default=dict, verbose_name="Ответ YooKassa"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
