# Generated by Django 5.2.15 on 2026-06-04 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_scanned",
                    models.CharField(max_length=200, verbose_name="Токен"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("valid", "✓ Действителен"),
                            ("used", "Уже использован"),
                            ("invalid", "Недействителен"),
                            ("canceled", "Отменён"),
                            ("expired", "Истёк"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "scanned_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Сканировал"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(null=True, verbose_name="IP"),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Устройство"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkin_logs",
                        to="orders.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог прохода",
                "verbose_name_plural": "Журнал проходов",
                "ordering": ["-created_at"],
            },
        ),
    ]
