# Generated by Django 5.2.15 on 2026-06-04 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="Получатель"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                (
                    "template_name",
                    models.CharField(max_length=100, verbose_name="Шаблон"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("sent", "Отправлен"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлен"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="orders.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог email",
                "verbose_name_plural": "Логи email",
                "ordering": ["-created_at"],
            },
        ),
    ]
